[colors]
draw_bold_text_with_bright_colors = true
[colors.primary]
background = "#14121C"
foreground = "#968081"

[env]
TERM = "xterm-256color"

[font]
size = 18
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular"}
bold = { family = "JetBrainsMono Nerd Font Propo", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font Propo", style = "italic"}

[selection]
save_to_clipboard = false

[window.padding]
x = 3
y = 3

[window]
decorations = "buttonless"
opacity = 0.83

